run_config:
  resume_from_checkpoint: false
  force_regenerate_data: true

curriculum:
  stage0:
    name: "Debug Stage"
    data_dir: "data/debug"
    epochs: 2
    batch_size: 2
    learning_rate: 0.001
    num_workers: 0
    resume_from_last_stage: false
    cell_size: 4
    mosaic_params:
      num_mosaics: 5
      val_mosaics: 2
      mosaic_size: 512

data_params:
  num_train_samples: 50
  num_val_samples: 10
  min_stars: 10
  max_stars: 50
  image_size: 256
  max_capacity_per_cell: 3
  shape_size: 7
  GLOBAL_STRETCH_SCALE: 10.0

loss_params:
  lambda_prob: 1.0
  lambda_pos: 1.0
  lambda_flux: 1.0
  lambda_bg: 1.0
  lambda_diffraction_reg: 10.0
  focal_alpha: 0.50
  focal_gamma: 2.0
